from django.urls import path

from mailing import ops_views, views

app_name = "mailing"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("health/", views.health, name="health"),
    path("health/ready", views.readiness, name="readiness"),
    path("internal/ops/status", ops_views.status, name="taskdeck_status"),
    path("campaigns/", views.campaign_list, name="campaign_list"),
    path("campaigns/new/", views.campaign_create, name="campaign_create"),
    path("campaigns/<int:campaign_id>/", views.campaign_detail, name="campaign_detail"),
    path("campaigns/<int:campaign_id>/edit/", views.campaign_edit, name="campaign_edit"),
    path("campaigns/<int:campaign_id>/queue/", views.campaign_queue, name="campaign_queue"),
    path("audiences/", views.audience_list, name="audience_list"),
    path("audiences/new/", views.audience_create, name="audience_create"),
    path("audiences/<int:audience_id>/", views.audience_detail, name="audience_detail"),
    path("audiences/<int:audience_id>/edit/", views.audience_edit, name="audience_edit"),
    path("audiences/<int:audience_id>/tags/new/", views.tag_create, name="tag_create"),
    path("tags/<int:tag_id>/", views.tag_detail, name="tag_detail"),
    path("tags/<int:tag_id>/edit/", views.tag_edit, name="tag_edit"),
    path("clients/", views.client_list, name="client_list"),
    path("clients/select/", views.client_select, name="client_select"),
    path("clients/new/", views.client_create, name="client_create"),
    path("clients/<int:client_id>/", views.client_detail, name="client_detail"),
    path("clients/<int:client_id>/edit/", views.client_edit, name="client_edit"),
    path(
        "clients/<int:client_id>/mailchimp/tag-mappings/",
        views.client_mailchimp_tag_mappings,
        name="client_mailchimp_tag_mappings",
    ),
    path(
        "clients/<int:client_id>/api-keys/create/",
        views.client_api_key_create,
        name="client_api_key_create",
    ),
    path(
        "clients/<int:client_id>/api-keys/<int:key_id>/revoke/",
        views.client_api_key_revoke,
        name="client_api_key_revoke",
    ),
    path("contacts/", views.contact_search, name="contact_search"),
    path("contacts/<str:contact_email>/", views.contact_detail, name="contact_detail"),
    path(
        "contacts/<str:contact_email>/state/",
        views.contact_state_update,
        name="contact_state_update",
    ),
    path(
        "contacts/<str:contact_email>/subscriptions/",
        views.contact_subscription_update,
        name="contact_subscription_update",
    ),
    path("contacts/<str:contact_email>/tags/add/", views.contact_tag_add, name="contact_tag_add"),
    path(
        "contacts/<str:contact_email>/tags/remove/",
        views.contact_tag_remove,
        name="contact_tag_remove",
    ),
    path("api-docs/", views.api_docs, name="api_docs"),
    path("api-docs/openapi.json", views.api_docs_json, name="api_docs_json"),
    path("api/workers/status", views.api_worker_status, name="api_worker_status"),
    path("templates/", views.template_catalog, name="template_catalog"),
    path("templates/<int:template_id>/", views.template_detail, name="template_detail"),
    path("transactional/queue/", views.transactional_queue, name="transactional_queue"),
    path(
        "transactional/messages/<int:message_id>/",
        views.transactional_message_detail,
        name="transactional_message_detail",
    ),
    path("t/o/<str:tracking_token>.gif", views.tracking_open, name="tracking_open"),
    path("t/c/<str:tracking_token>", views.tracking_click, name="tracking_click"),
    path("unsubscribe/<str:unsubscribe_token>", views.public_unsubscribe, name="public_unsubscribe"),
    path("webhooks/ses", views.ses_webhook, name="ses_webhook"),
    path("api/contacts.csv", views.api_contacts_csv, name="api_contacts_csv"),
    path("api/contacts/imports", views.api_contact_imports, name="api_contact_imports"),
    path("api/contacts/imports/csv", views.api_contact_imports_csv, name="api_contact_imports_csv"),
    path("api/contacts", views.api_contacts, name="api_contacts"),
    path("api/contacts/status", views.api_contact_status, name="api_contact_status"),
    path("api/contacts/erase", views.api_contact_erase, name="api_contact_erase"),
    path("api/contacts/preferences", views.api_contact_preferences, name="api_contact_preferences"),
    path("api/contacts/<int:contact_id>/tags", views.api_contact_tags, name="api_contact_tags"),
    path("api/contacts/<int:contact_id>/tags/<slug:tag_slug>", views.api_contact_tag, name="api_contact_tag"),
    path(
        "api/contacts/<int:contact_id>/verification",
        views.api_contact_verification,
        name="api_contact_verification",
    ),
    path("api/contacts/<int:contact_id>/validation", views.api_contact_validation, name="api_contact_validation"),
    path("api/contacts/<int:contact_id>/suppression", views.api_contact_suppression, name="api_contact_suppression"),
    path("api/contacts/<int:contact_id>/history", views.api_contact_history, name="api_contact_history"),
    path("api/client/senders", views.api_client_senders, name="api_client_senders"),
    path("api/client/mailchimp", views.api_client_mailchimp, name="api_client_mailchimp"),
    path(
        "api/client/mailchimp/tag-mappings",
        views.api_client_mailchimp_tag_mappings,
        name="api_client_mailchimp_tag_mappings",
    ),
    path("api/campaigns/<str:external_key>", views.api_campaign, name="api_campaign"),
    path("api/campaigns/<str:external_key>/queue", views.api_campaign_queue, name="api_campaign_queue"),
    path("api/campaigns/<str:external_key>/cancel", views.api_campaign_cancel, name="api_campaign_cancel"),
    path("api/campaigns/<str:external_key>/preview", views.api_campaign_preview, name="api_campaign_preview"),
    path("api/campaigns/<str:external_key>/test-send", views.api_campaign_test_send, name="api_campaign_test_send"),
    path("api/subscriptions/subscribe", views.api_subscribe, name="api_subscribe"),
    path("api/subscriptions/unsubscribe", views.api_unsubscribe, name="api_unsubscribe"),
    path(
        "api/subscriptions/request-verification",
        views.api_request_verification,
        name="api_request_verification",
    ),
    path("api/subscriptions/confirm", views.api_confirm, name="api_confirm"),
    path("api/recipient-lists/<str:list_key>", views.api_recipient_list, name="api_recipient_list"),
    path(
        "api/recipient-lists/<str:list_key>/members",
        views.api_recipient_list_members,
        name="api_recipient_list_members",
    ),
    path(
        "api/recipient-lists/<str:list_key>/members/bulk-upsert",
        views.api_recipient_list_bulk_upsert,
        name="api_recipient_list_bulk_upsert",
    ),
    path(
        "api/recipient-lists/<str:list_key>/members/reconcile",
        views.api_recipient_list_reconcile,
        name="api_recipient_list_reconcile",
    ),
    path(
        "api/recipient-lists/<str:list_key>/imports",
        views.api_recipient_list_imports,
        name="api_recipient_list_imports",
    ),
    path(
        "api/recipient-lists/<str:list_key>/imports/<int:job_id>",
        views.api_recipient_list_import,
        name="api_recipient_list_import",
    ),
    path(
        "api/recipient-lists/<str:list_key>/transactional-send",
        views.api_recipient_list_transactional_send,
        name="api_recipient_list_transactional_send",
    ),
    path(
        "api/transient-recipient-lists/transactional-send",
        views.api_transient_recipient_list_transactional_send,
        name="api_transient_recipient_list_transactional_send",
    ),
    path(
        "api/recipient-lists/<str:list_key>/members/<str:source_object_key>",
        views.api_recipient_list_member,
        name="api_recipient_list_member",
    ),
    path(
        "api/transactional/templates/<slug:template_key>",
        views.api_transactional_template,
        name="api_transactional_template",
    ),
    path("api/transactional/send", views.api_transactional_send, name="api_transactional_send"),
    path(
        "api/transactional/messages/<int:message_id>",
        views.api_transactional_message_status,
        name="api_transactional_message_status",
    ),
]
