# Generated by Django 6.0.5 on 2026-09-07 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0025_client_relay_webhook_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='markdown_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactionalmessage',
            name='template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('markdown_body', models.TextField(blank=True)),
                ('required_context', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='mailing.emailtemplate')),
            ],
            options={
                'db_table': 'email_template_versions',
                'ordering': ['template_id', '-version'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='unique_email_template_version')],
            },
        ),
    ]
