# Generated by Django 6.0.5 on 2026-09-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0025_client_relay_webhook_fields'),
        ('mailing', '0026_emailtemplate_category_emailtemplate_markdown_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2048)),
                ('signing_secret', models.CharField(max_length=255)),
                ('previous_signing_secret', models.CharField(blank=True, max_length=255)),
                ('secret_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'callback_endpoints',
                'ordering': ['client__organization__slug', 'client__slug'],
            },
        ),
        migrations.CreateModel(
            name='ClientCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(editable=False, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('client_reference', models.CharField(blank=True, max_length=255)),
                ('message_kind', models.CharField(blank=True, max_length=20)),
                ('message_ref', models.CharField(blank=True, max_length=64)),
                ('template_key', models.CharField(blank=True, max_length=120)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
                ('body', models.TextField()),
                ('body_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('response_status_class', models.CharField(blank=True, max_length=8)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'client_callbacks',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='callbackendpoint',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='callback_endpoint', to='mailing.client'),
        ),
        migrations.AddField(
            model_name='clientcallback',
            name='campaign_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_callbacks', to='mailing.campaignrecipient'),
        ),
        migrations.AddField(
            model_name='clientcallback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_callbacks', to='mailing.client'),
        ),
        migrations.AddField(
            model_name='clientcallback',
            name='email_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_callbacks', to='mailing.emailevent'),
        ),
        migrations.AddField(
            model_name='clientcallback',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='callbacks', to='mailing.callbackendpoint'),
        ),
        migrations.AddField(
            model_name='clientcallback',
            name='transactional_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_callbacks', to='mailing.transactionalmessage'),
        ),
        migrations.AddIndex(
            model_name='clientcallback',
            index=models.Index(fields=['status', 'next_attempt_at'], name='client_cb_status_next_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcallback',
            index=models.Index(fields=['client', 'status', 'created_at'], name='client_cb_cli_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcallback',
            index=models.Index(fields=['client', 'message_kind', 'message_ref', 'sequence'], name='client_cb_msg_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcallback',
            constraint=models.UniqueConstraint(fields=('client', 'event_id'), name='unique_client_callback_event'),
        ),
    ]
