# Generated by Django 6.0.5 on 2026-09-29 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0027_callbackendpoint_clientcallback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('address', 'Exact address'), ('domain', 'Whole domain')], default='address', max_length=10)),
                ('value', models.CharField(max_length=320)),
                ('reason', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'blocked_senders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InboundAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_part', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inbound_addresses',
                'ordering': ['domain', 'local_part'],
                'constraints': [models.UniqueConstraint(fields=('local_part', 'domain'), name='unique_inbound_address')],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_id', models.CharField(blank=True, max_length=512)),
                ('state', models.CharField(choices=[('received', 'Received'), ('blocked', 'Blocked sender'), ('read', 'Read')], default='received', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('snippet', models.TextField(blank=True)),
                ('from_header', models.CharField(blank=True, max_length=998)),
                ('sender_address', models.CharField(blank=True, db_index=True, max_length=320)),
                ('sender_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('to_header', models.CharField(blank=True, max_length=998)),
                ('cc_header', models.CharField(blank=True, max_length=998)),
                ('recipient', models.CharField(blank=True, db_index=True, max_length=320)),
                ('recipient_domain', models.CharField(blank=True, max_length=255)),
                ('recipient_address', models.CharField(blank=True, max_length=320)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('raw_bucket', models.CharField(blank=True, max_length=255)),
                ('raw_key', models.CharField(blank=True, max_length=1024)),
                ('body_text_key', models.CharField(blank=True, max_length=1024)),
                ('body_html_key', models.CharField(blank=True, max_length=1024)),
                ('spam_verdict', models.CharField(blank=True, max_length=64)),
                ('virus_verdict', models.CharField(blank=True, max_length=64)),
                ('spf_verdict', models.CharField(blank=True, max_length=64)),
                ('dkim_verdict', models.CharField(blank=True, max_length=64)),
                ('dmarc_verdict', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_messages', to='mailing.blockedsender')),
                ('inbound_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='mailing.inboundaddress')),
            ],
            options={
                'db_table': 'inbound_messages',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='blockedsender',
            name='origin_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_blocks', to='mailing.inboundmessage'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['state', 'created_at'], name='inbound_msg_state_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['sender_address', 'created_at'], name='inbound_msg_sender_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundmessage',
            index=models.Index(fields=['recipient', 'created_at'], name='inbound_msg_rcpt_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('message_id',), name='unique_nonempty_inbound_message_id'),
        ),
        migrations.AddIndex(
            model_name='blockedsender',
            index=models.Index(fields=['scope', 'value'], name='blocked_sender_scope_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockedsender',
            constraint=models.UniqueConstraint(fields=('scope', 'value'), name='unique_blocked_sender_scope_value'),
        ),
    ]
