# Generated by Django 6.0.5 on 2026-10-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0029_adminapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('snapshotting', 'Snapshotting'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payloads', models.JSONField(default=list)),
                ('correlation_id', models.UUIDField()),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dispatch', to='mailing.campaign')),
            ],
            options={
                'db_table': 'campaign_dispatches',
                'indexes': [models.Index(fields=['enqueued_at'], name='campaign_dispatch_pending_idx')],
            },
        ),
    ]
