# Generated by Django 6.0.7 on 2026-08-06 23:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("result_id", models.CharField(max_length=255, unique=True)),
                ("project", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("func", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("dead", "Dead"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("owner_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("progress_current", models.IntegerField(blank=True, null=True)),
                ("progress_total", models.IntegerField(blank=True, null=True)),
                ("enqueued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("attempt", models.IntegerField(default=1)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("error", models.TextField(blank=True)),
                ("entity_type", models.CharField(blank=True, max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="taskdeck.taskrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-enqueued_at"],
                "indexes": [
                    models.Index(fields=["project", "-enqueued_at"], name="td_run_proj_enq_idx"),
                    models.Index(fields=["status", "-enqueued_at"], name="td_run_status_enq_idx"),
                    models.Index(fields=["name", "-finished_at"], name="td_run_name_fin_idx"),
                ],
            },
        ),
    ]
