# Generated by Django 6.0.5 on 2026-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_lease_expires_at_alter_job_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
