# Generated by Django 6.0.5 on 2026-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_schedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('pid', models.PositiveIntegerField()),
                ('ticked_at', models.DateTimeField()),
                ('schedules_fired', models.PositiveIntegerField(default=0)),
                ('expired_leases', models.PositiveIntegerField(default=0)),
                ('recovered_jobs', models.PositiveIntegerField(default=0)),
                ('campaigns_dispatched', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'scheduler heartbeat',
                'verbose_name_plural': 'scheduler heartbeat',
                'db_table': 'relay_scheduler_heartbeat',
            },
        ),
    ]
