#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: $0 [--environment sandbox|production] <git-commit>" >&2
}

help() {
  cat <<HELP
Usage: $0 [--environment sandbox|production] <git-commit>

Deploy one Relay release on this host. The host is prepared by Terraform
(sandbox/relay or main/relay in DataTalksClub/aws-infra).

Options:
  --environment sandbox|production  Target environment. Default: sandbox.
  --help                            Show this help.

The environment selects the CloudWatch log group, the web listener address,
the release health check, and the environment-specific bootstrap of
/etc/relay/runtime.env. Sandbox keeps a local PostgreSQL container and Caddy;
production uses the RDS database and the shared load balancer, publishes the
web container on all interfaces, starts no PostgreSQL or Caddy, no inbound
mail ingress, and gives every container an explicit memory limit.
HELP
}

environment=sandbox
while [[ $# -gt 0 ]]; do
  case "$1" in
    --environment)
      if [[ $# -lt 2 ]]; then
        usage
        exit 2
      fi
      environment="$2"
      shift 2
      ;;
    --environment=*)
      environment="${1#*=}"
      shift
      ;;
    --help)
      help
      exit 0
      ;;
    --)
      shift
      break
      ;;
    -*)
      usage
      exit 2
      ;;
    *)
      break
      ;;
  esac
done

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi
release="$1"

case "$environment" in
  sandbox) ;;
  production) ;;
  *)
    usage
    exit 2
    ;;
esac

case "$environment" in
  sandbox)
    log_group="/relay/sandbox/host"
    web_bind="127.0.0.1:8000"
    public_health_url="https://relay.dtcdev.click/health/ready"
    ;;
  production)
    log_group="/relay/production/host"
    web_bind="0.0.0.0:8000"
    # The production host is private behind the shared ALB; there is no public
    # health URL to poll from outside. The local readiness check and the
    # in-host smoke test below are the release gate.
    public_health_url=""
    ;;
esac

readonly environment
readonly release
readonly app_dir="/opt/relay"
readonly runtime_env="/etc/relay/runtime.env"
readonly infra_env="/etc/relay/infrastructure.env"
readonly image="relay:${release}"
readonly network="relay"
readonly log_group
readonly web_bind
readonly public_health_url

if [[ ! -f "$infra_env" ]]; then
  echo "missing $infra_env; Terraform bootstrap has not completed" >&2
  exit 1
fi

install -d -m 0755 /etc/relay /var/lib/relay/postgres /var/lib/relay/caddy-data /var/lib/relay/caddy-config
git config --system --get-all safe.directory | grep -Fxq "$app_dir" || \
  git config --system --add safe.directory "$app_dir"

secret_from_secrets_manager() {
  local key="$1"
  local arn region
  arn="$(sed -n "s/^${key}=//p" "$infra_env")"
  if [[ -z "$arn" ]]; then
    echo "${key} is missing from $infra_env" >&2
    exit 1
  fi
  region="$(sed -n 's/^AWS_REGION=//p' "$infra_env")"
  aws --region "$region" secretsmanager get-secret-value \
    --secret-id "$arn" \
    --query SecretString \
    --output text
}

if [[ ! -f "$runtime_env" ]]; then
  umask 077
  if [[ "$environment" == sandbox ]]; then
    secret_key="$(openssl rand -hex 48)"
    postgres_password="$(openssl rand -hex 32)"
    api_public_id="dtccourses$(openssl rand -hex 4)"
    api_secret="$(openssl rand -hex 32)"
    status_token="$(openssl rand -hex 32)"
    cat >"$runtime_env" <<ENV
DEBUG=False
SECRET_KEY=${secret_key}
ALLOWED_HOSTS=relay.dtcdev.click,127.0.0.1,localhost
CSRF_TRUSTED_ORIGINS=https://relay.dtcdev.click
DATABASE_URL=postgresql://relay:${postgres_password}@127.0.0.1:5432/relay
POSTGRES_DB=relay
POSTGRES_USER=relay
POSTGRES_PASSWORD=${postgres_password}
DEFAULT_FROM_EMAIL=DataTalksClub Relay <relay@dtcdev.click>
AWS_SES_REGION=us-east-1
AWS_SES_CONFIGURATION_SET=datamailer-sandbox
RELAY_API_DOCS_BASE_URL=https://relay.dtcdev.click
RELAY_SES_MAX_SEND_RATE=14
RELAY_BOOTSTRAP_API_KEY=relay_${api_public_id}_${api_secret}
TASKDECK_STATUS_TOKEN=${status_token}
RELAY_REQUIRE_TASK_ROLES=True
RELAY_WORKER_STATUS_SYSTEMD_ENABLED=False
ENV
  else
    # Production keeps every name-derived value in infrastructure.env
    # (ALLOWED_HOSTS including the instance IP, CSRF_TRUSTED_ORIGINS,
    # DEFAULT_FROM_EMAIL, AWS_SES_REGION, AWS_SES_CONFIGURATION_SET,
    # PUBLIC_BASE_URL, AUTH_*). This file holds only secrets: the Django
    # secret key and DATABASE_URL come from Secrets Manager, and the status
    # token is generated here. The client API key is generated by
    # scripts/provision_production_tenant.sh, not here.
    secret_key="$(secret_from_secrets_manager RELAY_SECRET_KEY_SECRET_ARN)"
    database_url="$(secret_from_secrets_manager RELAY_DATABASE_URL_SECRET_ARN)"
    status_token="$(openssl rand -hex 32)"
    cat >"$runtime_env" <<ENV
DEBUG=False
SECRET_KEY=${secret_key}
DATABASE_URL=${database_url}
RELAY_API_DOCS_BASE_URL=https://relay.datatalks.club
TASKDECK_STATUS_TOKEN=${status_token}
RELAY_REQUIRE_TASK_ROLES=True
RELAY_WORKER_STATUS_SYSTEMD_ENABLED=False
ENV
  fi
  chmod 0600 "$runtime_env"
fi

set_runtime_value() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "$runtime_env"; then
    sed -i "s|^${key}=.*$|${key}=${value}|" "$runtime_env"
  else
    printf '%s=%s\n' "$key" "$value" >>"$runtime_env"
  fi
}

if [[ "$environment" == sandbox ]]; then
  set_runtime_value DEFAULT_FROM_EMAIL 'DataTalksClub Relay <relay@dtcdev.click>'
  set_runtime_value AWS_SES_REGION us-east-1
  set_runtime_value AWS_SES_CONFIGURATION_SET datamailer-sandbox
  set_runtime_value RELAY_SES_MAX_SEND_RATE 14
fi

grep -q '^RELAY_EMAIL_SEND_ROLE_ARN=' "$infra_env" || {
  echo "RELAY_EMAIL_SEND_ROLE_ARN is missing from $infra_env" >&2
  exit 1
}

email_role_arn="$(sed -n 's/^RELAY_EMAIL_SEND_ROLE_ARN=//p' "$infra_env")"
if ! grep -q '^RELAY_TASK_ROLE_ARNS=' "$runtime_env"; then
  printf 'RELAY_TASK_ROLE_ARNS={"email.send":"%s"}\n' "$email_role_arn" >>"$runtime_env"
fi

if [[ ! -d "$app_dir/.git" ]]; then
  if [[ -f "$app_dir/README" ]]; then
    mv "$app_dir/README" /var/lib/relay/bootstrap-readme
  fi
  git -C "$app_dir" init
fi
if git -C "$app_dir" remote get-url origin >/dev/null 2>&1; then
  git -C "$app_dir" remote set-url origin https://github.com/DataTalksClub/relay.git
else
  git -C "$app_dir" remote add origin https://github.com/DataTalksClub/relay.git
fi
git -C "$app_dir" fetch --prune origin main
git -C "$app_dir" checkout --force "$release"
git -C "$app_dir" clean -ffd -e .env

docker network inspect "$network" >/dev/null 2>&1 || docker network create "$network"
docker build --pull --tag "$image" "$app_dir"
if [[ "$environment" == sandbox ]]; then
  docker pull postgres:17-alpine
  docker pull caddy:2-alpine
fi

log_options=(
  --log-driver awslogs
  --log-opt awslogs-region=eu-west-1
  --log-opt "awslogs-group=${log_group}"
)

# The production host has 2 GiB and no PostgreSQL, so every container carries
# an explicit memory limit (the main/relay host contract). The sandbox host
# keeps its historical limits-free invocations.
memory_args=()
set_memory_args() {
  memory_args=()
  if [[ "$environment" != production ]]; then
    return 0
  fi
  case "$1" in
    relay-web) memory_args=(--memory 384m) ;;
    relay-worker) memory_args=(--memory 512m) ;;
    relay-scheduler) memory_args=(--memory 96m) ;;
    relay-ses-ingress) memory_args=(--memory 128m) ;;
    relay-cmp-callbacks) memory_args=(--memory 96m) ;;
    relay-recipient-imports) memory_args=(--memory 128m) ;;
  esac
}

replace_container() {
  local name="$1"
  shift
  docker rm -f "$name" >/dev/null 2>&1 || true
  docker run --detach --name "$name" --restart unless-stopped \
    "${memory_args[@]}" \
    "${log_options[@]}" --log-opt "awslogs-stream=${name}" "$@"
}

if [[ "$environment" == sandbox ]]; then
  set_memory_args relay-postgres
  replace_container relay-postgres \
    --env-file "$runtime_env" \
    --publish 127.0.0.1:5432:5432 \
    --volume /var/lib/relay/postgres:/var/lib/postgresql/data \
    postgres:17-alpine

  for _ in $(seq 1 60); do
    if docker exec relay-postgres pg_isready -U relay -d relay >/dev/null 2>&1; then
      break
    fi
    sleep 2
  done
  docker exec relay-postgres pg_isready -U relay -d relay
fi

run_app() {
  docker run --rm --network host \
    --env-file "$infra_env" \
    --env-file "$runtime_env" \
    "$image" "$@"
}

run_app python manage.py migrate --noinput
run_app python manage.py collectstatic --noinput

if [[ "$environment" == sandbox ]]; then
  run_app python manage.py provision_client_scope \
    --organization datatalksclub \
    --organization-name DataTalksClub \
    --audience dtc-courses \
    --audience-name "DataTalksClub Courses" \
    --client dtc-courses \
    --client-name "DTC Courses"
  run_app python manage.py provision_client_api_key \
    --organization datatalksclub \
    --client dtc-courses \
    --name sandbox-deployment
  run_app python manage.py set_client_senders dtc-courses \
    --organization datatalksclub \
    --default-sender courses \
    --sender 'courses=DataTalks.Club Courses <courses@dtcdev.click>' \
    --sender 'no-reply=DataTalksClub <no-reply@dtcdev.click>'
else
  bash "$app_dir/scripts/provision_production_tenant.sh"
fi

app_container_args=(
  --network host
  --env-file "$infra_env"
  --env-file "$runtime_env"
  "$image"
)

set_memory_args relay-web
replace_container relay-web "${app_container_args[@]}" \
  gunicorn --bind "$web_bind" --workers 2 --timeout 60 --access-logfile - relay.wsgi:application
set_memory_args relay-worker
replace_container relay-worker "${app_container_args[@]}" \
  python manage.py db_worker --interval 1
set_memory_args relay-scheduler
replace_container relay-scheduler "${app_container_args[@]}" \
  python manage.py run_relay_scheduler --interval 15
set_memory_args relay-ses-ingress
replace_container relay-ses-ingress "${app_container_args[@]}" \
  python manage.py drain_sqs_ingress ses-webhooks --batch-size 10 --wait-time 20
if [[ "$environment" == sandbox ]]; then
  set_memory_args relay-inbound-ingress
  replace_container relay-inbound-ingress "${app_container_args[@]}" \
    python manage.py drain_sqs_ingress inbound-email --batch-size 10 --wait-time 20
fi
set_memory_args relay-cmp-callbacks
replace_container relay-cmp-callbacks "${app_container_args[@]}" \
  python manage.py process_cmp_callbacks --batch-size 25 --idle-sleep 5
set_memory_args relay-recipient-imports
replace_container relay-recipient-imports "${app_container_args[@]}" \
  python manage.py process_recipient_list_imports --batch-size 10 --idle-sleep 5

if [[ "$environment" == sandbox ]]; then
  replace_container relay-caddy \
    --network host \
    --entrypoint caddy \
    --volume "$app_dir/deploy/Caddyfile:/etc/caddy/Caddyfile:ro" \
    --volume /var/lib/relay/caddy-data:/data \
    --volume /var/lib/relay/caddy-config:/config \
    caddy:2-alpine run --config /etc/caddy/Caddyfile --adapter caddyfile
fi

if [[ "$environment" == sandbox ]]; then
  required_containers=(
    relay-postgres
    relay-web
    relay-worker
    relay-scheduler
    relay-ses-ingress
    relay-inbound-ingress
    relay-cmp-callbacks
    relay-recipient-imports
    relay-caddy
  )
else
  required_containers=(
    relay-web
    relay-worker
    relay-scheduler
    relay-ses-ingress
    relay-cmp-callbacks
    relay-recipient-imports
  )
fi

for _ in $(seq 1 60); do
  if curl --fail --silent http://127.0.0.1:8000/health/ready >/dev/null; then
    break
  fi
  sleep 2
done
curl --fail --show-error --silent http://127.0.0.1:8000/health/ready

for container in "${required_containers[@]}"; do
  [[ "$(docker inspect --format '{{.State.Running}}' "$container")" == "true" ]]
done

run_app python scripts/smoke_test_relay.py --base-url http://127.0.0.1:8000
if [[ "$environment" == sandbox ]]; then
  run_app python scripts/upsert_cmp_templates.py \
    --base-url http://127.0.0.1:8000
fi

if [[ -n "$public_health_url" ]]; then
  curl --fail --show-error --silent --retry 20 --retry-delay 3 "$public_health_url"
fi
echo "Relay ${environment} deployed: ${release}"
